---
# Software installation
- name: ensure packages are installed
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - apache2
    - backuppc
    - python-passlib # ansible htpasswd support
    - rsync
  tags:
    - backuppc
    - packages

- name: adjust apache2 config
  lineinfile:
    name: '/etc/apache2/ports.conf'
    regexp: '^Listen.*80$'
    line: 'Listen localhost:80'
    state: present
  notify: restart apache2

- name: set pool symlink
  file:
    src: '/var/lib/backuppc/pc'
    dest: '/etc/backuppc/pc'
    owner: 'backuppc'
    group: 'backuppc'
    state: link 

# Software configuration
- name: copy config.pl
  template:
    src: config.pl.j2
    dest: '/etc/backuppc/config.pl'
    mode: 'u=rw,g=r,o=r'
    owner: 'backuppc'
    group: 'www-data'
    backup: yes
  notify:
    - restart backuppc
    - restart apache2

# ssh key
- name: generate a ssh key
  user:
    name: 'backuppc'
    generate_ssh_key: yes
  register: backuppc_server_ssh_key
  tags:
    - backuppc
    - ssh
    - clients

- name: fetch generated public ssh key
  fetch:
    src: '/var/lib/backuppc/.ssh/id_rsa.pub'
    dest: '/tmp/backuppc_ssh.pub'
  when: backuppc_server_ssh_key|changed
  register: ssh_key_fetched
  tags:
    - backuppc
    - ssh
    - clients
    - configuration

- name: add users to backuppc htpasswd file
  htpasswd:
    path: /etc/backuppc/htpasswd
    name: "{{ item.name }}"
    password: "{{ item.pass }}"
    owner: 'backuppc'
    group: 'www-data'
    mode: 'u=rw,g=r,o='
  with_items: "{{ backuppc_users }}"
  tags:
    - backuppc
    - website
    - credientals

# hosts configuration
- name: config hosts
  include: config_hosts.yml

# loop over backuppc_hosts is done inside manage_hosts.yml
- name: manage remote hosts
  include: manage_hosts.yml
  when: backuppc_manage_hosts

