---
# Software installation
- name: ensure packages are installed
  apt: pkg={{item}} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - backuppc
    - apache2
    - rsync
    - python-passlib # ansible htpasswd support
  tags:
    - backuppc
    - packages

- name: set pool symlink
  file:
    src=/var/lib/backuppc/pc
    dest=/etc/backuppc/pc
    state=link 
    owner=backuppc
    group=backuppc

# Software configuration
- name: copy config.pl
  template:
    src=config.pl.j2
    dest=/etc/backuppc/config.pl
    mode="u=rw,g=r,o=r"
    owner=backuppc
    group=www-data
  notify:
    - restart backuppc
    - restart apache2

#  host setup
- name: create hosts
  template:
    src=hosts.j2
    dest=/etc/backuppc/hosts
    mode="u=rw,g=r,o=r"
    owner=backuppc
    group=www-data
  notify:
    - restart backuppc
  tags:
    - backuppc
    - configuration
    - clients

- name: create hosts configuration
  template:
    dest="/etc/backuppc/{{ item.name }}.pl"
    src="backuppc-{{ item.os }}-{{ item.type }}.j2"
    mode="u=rw,g=r,o="
    owner=backuppc
    group=www-data
  with_items: backuppc_hosts
  notify:
    - restart backuppc
  tags:
    - backuppc
    - configuration
    - clients

# ssh key
- name: generate a ssh key
  user:
    name=backuppc
    generate_ssh_key=yes
  register: ssh_key_generation
  tags:
    - backuppc
    - ssh
    - clients

- name: fetch generated public ssh key
  fetch:
    src=/var/lib/backuppc/.ssh/id_rsa.pub
    dest=/tmp/fetched
  when: ssh_key_generation|changed
  register: ssh_key_fetched
  tags:
    - backuppc
    - ssh
    - clients
    - configuration

- name: add users to backuppc htpasswd file
  htpasswd:
    path: /etc/backuppc/htpasswd
    name: "{{ item.name }}"
    password: "{{ item.pass }}"
    owner: backuppc
    group: www-data
    mode: 0640
  with_items: backuppc_users
  tags:
    - backuppc
    - web site
    - credientals
