# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.vm.define "ubuntu-trusty" do |vagrant1|
    vagrant1.vm.box = "ubuntu/trusty64"
    vagrant1.vm.synced_folder ".", "/vagrant", disabled: true
    vagrant1.ssh.forward_agent = true
    vagrant1.vm.network "forwarded_port", guest: 80, host: 18080

    vagrant1.vm.provision "ansible" do |ansible|
      ansible.playbook = "test.yml"
    end
  end

  config.vm.define "ubuntu-bionic" do |vagrant1|
    vagrant1.vm.box = "ubuntu/bionic64"
    vagrant1.vm.synced_folder ".", "/vagrant", disabled: true
    vagrant1.ssh.forward_agent = true
    vagrant1.vm.network "forwarded_port", guest: 80, host: 28080

    vagrant1.vm.provision "ansible" do |ansible|
      ansible.playbook = "test.yml"
    end
  end

  config.vm.define "centos7" do |vagrant1|
    vagrant1.vm.box = "centos/7"
    vagrant1.vm.synced_folder ".", "/vagrant", disabled: true
    vagrant1.ssh.forward_agent = true
    vagrant1.vm.network "forwarded_port", guest: 80, host: 38080

    vagrant1.vm.provision "ansible" do |ansible|
      ansible.playbook = "test.yml"
    end
  end

end
